// This file is automatically generated by Firebase Studio.
// Do not edit it manually.
//
// Your web app's Firebase configuration
export const firebaseConfig = {
  apiKey: "AIzaSyB_PA5G02q4aJdA6QaJzUEjP5eMyN2aX6c",
  authDomain: "dev-prototyper-7969f.firebaseapp.com",
  projectId: "dev-prototyper-7969f",
  storageBucket: "dev-prototyper-7969f.appspot.com",
  messagingSenderId: "776739649583",
  appId: "1:776739649583:web:7f9518d8e5743f553c6569"
};
